### ISSUE TITLE
Module build failed: Error: No ESLint configuration found

### ISSUE THREAD

**Issue by pshenoynj** [creativetimofficial/ct-vue-paper-dashboard-pro#110]
I just purchased paper-dashboard-pro template and i am trying to run it with "npm run dev" and i see the following errors. (FYI: I tried the free version first and tested it working before purchasing the pro version). Need help resolving this issue.

npm run dev

> vue-paper-dashboard-pro@1.1.0 dev /Users/abc/workspace/ui
> cross-env ENABLE_ESLINT=true node build/dev-server.js

> Starting dev server...

 ERROR  Failed to compile with 1 errors                                             

Module build failed: Error: No ESLint configuration found.
    at getLocalConfig (/Users/abc/workspace/ui/node_modules/eslint/lib/config.js:162:35)
    at Config.getConfig (/Users/abc/workspace/ui/node_modules/eslint/lib/config.js:260:26)
    at processText (/Users/abc/workspace/ui/node_modules/eslint/lib/cli-engine.js:224:33)
    at CLIEngine.executeOnText (/Users/abc/workspace/ui/node_modules/eslint/lib/cli-engine.js:754:26)
    at lint (/Users/abc/workspace/ui/node_modules/eslint-loader/index.js:218:17)
    at Object.module.exports (/Users/abc/workspace/ui/node_modules/eslint-loader/index.js:213:21)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
> Listening at http://localhost:8000

unable to access the web page at http://localhost:8000
Cannot GET /

**Comment by sajadevo** [comment]
Hey there

We've updated the product and this issue is fixed now, please update to the latest version of the product.

Regards,
Sajad
