### ISSUE TITLE
Error install Eslint (@vue/eslint) 

### ISSUE THREAD

**Issue by criscafa123** [creativetimofficial/ct-vue-paper-dashboard-pro#63]
After executing  the command `vue add @vue/eslint --config standard --lintOn save`
The project generates the following error in the console:

`🚀  Invoking generator for @vue/cli-plugin-eslint...
 ERROR  SyntaxError: Unexpected token / in JSON at position 703
SyntaxError: Unexpected token / in JSON at position 703
    at JSON.parse (<anonymous>)
    at Object.read (C:\Users\cristian.castellanos\AppData\Roaming\npm\node_modules\@vue\cli\lib\util\configTransforms.js:44:30)
    at ConfigTransform.transform (C:\Users\cristian.castellanos\AppData\Roaming\npm\node_modules\@vue\cli\lib\ConfigTransform.js:25:30)
    at extract (C:\Users\cristian.castellanos\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:139:37)
    at Generator.extractConfigFiles (C:\Users\cristian.castellanos\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:152:9)
    at Generator.generate (C:\Users\cristian.castellanos\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:114:10)
    at runGenerator (C:\Users\cristian.castellanos\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:121:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

**Comment by criscafa123** [comment]
@cristijora The error is solved, only removes .eslintrc file. Thanks.

"@vue/cli-plugin-eslint": "^3.0.0-beta.9" and "@vue/eslint-config-prettier": "^3.0.0-beta.9", do not exist in the package.json
