### ISSUE TITLE
failure running npm run dev after install

### ISSUE THREAD

**Issue by reidw7** [creativetimofficial/ct-vue-paper-dashboard-pro#92]
$ npm run dev

> vue-paper-dashboard-pro@2.0.0 dev /path/to/portal
> vue-cli-service serve --open

/path/to/portal/node_modules/open/index.js:16
const wslToWindowsPath = async path => {
                               ^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/path/to/portal/node_modules/@vue/cli-shared-utils/lib/openBrowser.js:9:14)

npm ERR! Linux 4.14.88-88.76.amzn2.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! vue-paper-dashboard-pro@2.0.0 dev: `vue-cli-service serve --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-paper-dashboard-pro@2.0.0 dev script 'vue-cli-service serve --open'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-paper-dashboard-pro package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     vue-cli-service serve --open
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-paper-dashboard-pro
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-paper-dashboard-pro
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /path/to/portal/npm-debug.log

**Comment by reidw7** [comment]
I upgraded Node and that did it. Would be helpful if your documentation listed what the minimum version needed for Node was
